version: '3'

services:
  web:
    build: .
    command: ./run_app.sh
    ports:
    - "8000:8000"
    depends_on:
    - db
  db:
    image: postgres
  unittest:
    build: .
    command: ./run_tests.sh
    depends_on:
    - db

